chore(web-console): Small UI fixes related to Tables
questdb/ui pull request #309
Opened 2024-07-17 14:32 UTC by insmac

- Remove the `+` icon in the Tables header - it will come back when the Create Table view is opened in the left side of the screen.
- Fix for clicking the disabled `Create Table` icon in read-only mode - it should not be possible to show it and clicking the icon should be a no-op.
- Fix table filter: it should show only the tables with a match and highlight.

2024-07-17 14:34 UTC, bluestreak01 requested changes
could you add a test to ensure disabled button cannot be toggled?

2024-07-18 08:46 UTC, javier commented
![image](https://github.com/user-attachments/assets/3c3ce62c-09fa-4deb-a7db-bd99acb169ca)

I can select now table columns, but no table names. Since table names are shown in an autocompletion drop down right after typing `FROM` or `JOIN` this is not as bad, but it would be nicer if we have it, as some people might be used to just type the table name and enter to get the contents without writing `SELECT * FROM`

2024-07-18 11:14 UTC, javier commented
Restested after last commit and copying functionality works fine now. Thanks!

2024-07-18 12:34 UTC, bluestreak01 approved these changes

2024-07-18 12:34 UTC, merged