WIP: multi buffer support in editor
questdb/ui pull request #65
Opened 2022-10-06 16:48 UTC by argshook

2022-10-26 10:35 UTC, insmac commented
I have found two small things:

1. When you have only one tab, `Close` in tab context menu should be disabled
2. I think renaming should not allow empty values

<img width="187" alt="CleanShot 2022-10-26 at 12 33 56@2x" src="https://user-images.githubusercontent.com/1871646/198004972-a53b3cfe-df56-452f-ab6d-9eb965dd701e.png">

2022-10-26 10:46 UTC, insmac submitted a review, later dismissed

2022-10-26 10:53 UTC, argshook commented
thanks @insmac, i fixed both issues you raised

2022-10-27 10:02 UTC, bluestreak01 requested changes
https://user-images.githubusercontent.com/7276403/198255510-f3d23f87-edcf-4f1b-9ae2-d87b0eef4e61.mp4

Messy editor behaviour when clicking on Tab

2022-10-27 10:05 UTC, bluestreak01 commented
I guess the intent to edit tab on double click. But double-click recognition is poor and even when system does resolve double click it acts as three operations: click + click + double-click

Editor cursor should not be moving when tab is clicked

2022-10-27 10:07 UTC, bluestreak01 commented
double-click only works on tab text, not on icon to left of the text. I find this counter-intuitive and clunky

2022-10-27 10:10 UTC, bluestreak01 commented
there is tab flicker when new tab is added:


https://user-images.githubusercontent.com/7276403/198257490-69edaf7c-24ef-4d33-a26f-313a490d57e8.mp4

2022-10-27 10:12 UTC, bluestreak01 commented
Not a fan of horizonal scrollbar:

![image](https://user-images.githubusercontent.com/7276403/198257846-bb63ccc3-8ce5-4c14-a273-cb489d1eb006.png)

2022-10-27 10:17 UTC, bluestreak01 commented
when there are too many tabs, UX is terrible:


https://user-images.githubusercontent.com/7276403/198258738-2897a8d6-7ae2-4883-926c-2b9aa807725e.mp4

Compare this to Chrome UX at the same position:

https://user-images.githubusercontent.com/7276403/198259034-e6eb7c21-f9f2-4eea-bf04-e2ee43665adb.mp4

2023-02-15 21:12 UTC, bluestreak01 commented
there is scroll bug - text I cannot access in editor:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/7276403/219165263-fa64045a-9a31-4dd4-b33b-e9ebe9aebba7.png">

2023-02-15 22:09 UTC, bluestreak01 commented
let me summarise my feedback

## ergonomics of the editor(s)

- very good overall, nothing major. Editor content is memorised, so is cursor and scroll position. 
- small resize issue, if you move horizontal splitter up and down, in certain positions editor doesn't resize correctly


## ergonomics of the tabs

- look and feel should be consistent with tabs that switch between grid and charts. In fact these should not be copies but rather full on button reuse if possible. I hope react allows for that
- I increasingly convince myself that google chrome's tab ergonomics are the best (and most proven)
 * new tab button should perhaps be more pronounced, including pronunciation of the hover. It should be entered
 * when tabs fill all available horizontal space "new tab" button should remain in place (it does already) and be perfectly entered (it isn't entered)
 * when space if filled and new tab is added, new and existing tabs should resize (shrink)
 * tabs should keep shrinking progressively. After some point lose text and keep shrinking icon until size at minimum
 * when tabs reach their absolute min size - the real estate of tabs should no longer change
 * ergonomics of tab close button are very good, close button stays in place while space is filled
 * tab resize should be animated (see how does chrome do animation)
 * opening and closing tabs should be animated in opposite directions (see chrome)
 * we can attempt to style all our tabs like chrome (https://adamschwartz.co/chrome-tabs/)

I am happy to help with all of this, but I will need pointers on how to do this in react efficiently. Perhaps some time to walk me thru the relevant code base ?

2023-02-16 14:37 UTC, argshook commented
@bluestreak01 thanks, Vlad, this is really helpful! I'll gromulate these points in my head and will get back to you

2025-03-12 19:37 UTC, closed without merging